AWSTemplateFormatVersion: 2010-09-09

Description: Template to spin up an ec2 instance

Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup    
      KeyName: ssh
      ImageId: 'ami-052efd3df9dad4825' 
      InstanceType: t2.micro
