version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  test_aws_cli_config:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          name: display aws version
          command: aws --version
      - run:
          name: list iam users
          command: aws iam list-users
      - run:
          name: list ec2 instances
          command: aws ec2 describe-instances

  create_infrastructure:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - checkout
      - run:
          name: create infrasturcture
          command: |
            aws cloudformation create-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --template-body file://template.yml --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=us-east-1

workflows:
  infratructure_creation:
    jobs:
      - test_aws_cli_config
      - create_infrastructure:
          requires:
            - test_aws_cli_config
