version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1

commands:
  destroy_infrastructure:
    steps:
      - run:
          name: destroy the creating infrastructure
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}

jobs:
  test_aws_cli_config:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run:
          name: display aws version
          command: aws --version
      - run:
          name: list iam users
          command: aws iam list-users
      - run:
          name: list ec2 instances
          command: aws ec2 describe-instances

  create_infrastructure:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - checkout
      - run:
          name: create infrasturcture
          command: |
            aws cloudformation deploy --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} --template-file template.yml --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=us-east-1
            aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Project,Values=${CIRCLE_WORKFLOW_ID}" --output text > /tmp/ip_address
      - persist_to_workspace:
          root: /tmp
          paths:
            - ip_address
      - destroy_infrastructure
  
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - add_ssh_keys:
          fingerprints: ["96:4a:db:8e:55:54:05:76:4f:5c:26:0a:de:d9:7d:0e"]
      - run:
          name: install ansible
          command: apk add --update ansible
      - run:
          name: display ip address
          command: cat /tmp/ip_address
      - run:
          name: create inventory file
          command: |
            echo "[host]" > inventory
            cat /tmp/ip_address >> inventory
            cat inventory
      - run:
          name: Run playbook and configure server
          command: ansible-playbook playbook.yml -i inventory
      - destroy_infrastructure

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: install curl
          command: apk add --update curl
      - run:
          name: query website endpoint
          command: |
            IP=$(cat /tmp/ip_address)
            URL="http://${IP}:3000"
            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi
      - run:
          name: display website content
          command: |
            IP=$(cat /tmp/ip_address)
            URL="http://${IP}:3000"
            curl ${URL}
      - destroy_infrastructure

workflows:
  deploy:
    jobs:
      - test_aws_cli_config
      - create_infrastructure:
          requires:
            - test_aws_cli_config
      - configure_infrastructure:
          requires:
            - create_infrastructure
      - smoke_test:
          requires:
            - configure_infrastructure
